# Generated by Django 5.2.4 on 2025-07-07 09:45

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la Catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du Client')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du Fournisseur')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Personne Contact')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='LieuStockage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du Lieu de Stockage')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Lieu de Stockage',
                'verbose_name_plural': 'Lieux de Stockage',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facturation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de Facturation')),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant Total')),
                ('est_payee', models.BooleanField(default=False, verbose_name='Est Payée')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('date_derniere_maj', models.DateTimeField(auto_now=True, verbose_name='Date Dernière Mise à Jour')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_produits_stock.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_facturation'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant du Paiement')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du Paiement')),
                ('mode_paiement', models.CharField(choices=[('CASH', 'Espèces'), ('VIREMENT', 'Virement Bancaire'), ('CARTE', 'Carte Bancaire'), ('CHEQUE', 'Chèque'), ('MOBILE_MONEY', 'Mobile Money'), ('AUTRE', 'Autre')], default='CASH', max_length=50, verbose_name='Mode de Paiement')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Référence du Paiement')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('date_derniere_maj', models.DateTimeField(auto_now=True, verbose_name='Date Dernière Mise à Jour')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion_produits_stock.facture', verbose_name='Facture Associée')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du Produit')),
                ('code_produit', models.CharField(max_length=50, unique=True, verbose_name='Code Produit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix Unitaire')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'Ajout")),
                ('date_derniere_maj', models.DateTimeField(auto_now=True, verbose_name='Date Dernière Mise à Jour')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_produits_stock.categorie', verbose_name='Catégorie')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_produits_stock.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('prix_unitaire_negocie', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix Unitaire Négocié')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gestion_produits_stock.facture', verbose_name='Facture')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_produits_stock.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de Facture',
                'verbose_name_plural': 'Lignes de Facture',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Quantité Actuelle')),
                ('date_derniere_maj', models.DateTimeField(auto_now=True, verbose_name='Date Dernière Mise à Jour')),
                ('lieu_stockage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_produits_stock.lieustockage', verbose_name='Lieu de Stockage')),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits_stock.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('AJUSTEMENT', 'Ajustement'), ('SORTIE_VENTE', 'Sortie (Vente)')], max_length=20, verbose_name='Type de Mouvement')),
                ('date_mouvement', models.DateTimeField(auto_now_add=True, verbose_name='Date du Mouvement')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_produits_stock.facture', verbose_name='Facture Associée')),
                ('lieu_stockage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_produits_stock.lieustockage', verbose_name='Lieu de Stockage')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits_stock.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Mouvement de Stock',
                'verbose_name_plural': 'Mouvements de Stock',
            },
        ),
    ]
