# Generated by Django 5.2.4 on 2025-08-07 19:34

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits_stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['nom'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['nom'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'ordering': ['nom'], 'verbose_name': 'Fournisseur', 'verbose_name_plural': 'Fournisseurs'},
        ),
        migrations.AlterModelOptions(
            name='lieustockage',
            options={'ordering': ['nom'], 'verbose_name': 'Lieu de Stockage', 'verbose_name_plural': 'Lieux de Stockage'},
        ),
        migrations.AlterModelOptions(
            name='lignefacture',
            options={'ordering': ['facture', 'produit'], 'verbose_name': 'Ligne de Facture', 'verbose_name_plural': 'Lignes de Facture'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['nom'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['produit', 'lieu_stockage'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-date_mouvement', 'produit'], 'verbose_name': 'Mouvement de Stock', 'verbose_name_plural': 'Mouvements de Stock'},
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='mode_paiement',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='date_ajout',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='lieu_stockage',
        ),
        migrations.AddField(
            model_name='categorie',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de Création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorie',
            name='date_derniere_maj',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Dernière Mise à Jour'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de Création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='date_derniere_maj',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Dernière Mise à Jour'),
        ),
        migrations.AddField(
            model_name='facture',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de Création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='date_derniere_maj',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Dernière Mise à Jour'),
        ),
        migrations.AddField(
            model_name='lieustockage',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de Création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lieustockage',
            name='date_derniere_maj',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Dernière Mise à Jour'),
        ),
        migrations.AddField(
            model_name='lieustockage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de Création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='date_derniere_maj',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Dernière Mise à Jour'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='total_ligne',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Ligne'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='methode_paiement',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE_BANCAIRE', 'Carte Bancaire'), ('VIREMENT', 'Virement Bancaire'), ('CHEQUE', 'Chèque'), ('MOBILE_MONEY', 'Mobile Money'), ('AUTRE', 'Autre')], default=1, max_length=50, verbose_name='Méthode de Paiement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Montant Payé'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de Création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='lieu_stockage_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_destination', to='gestion_produits_stock.lieustockage', verbose_name='Lieu Destination'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='lieu_stockage_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_source', to='gestion_produits_stock.lieustockage', verbose_name='Lieu Source'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom du Client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='gestion_produits_stock.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom du Fournisseur'),
        ),
        migrations.AlterField(
            model_name='lieustockage',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_facture', to='gestion_produits_stock.facture', verbose_name='Facture'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_produits_stock.produit', verbose_name='Produit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion_produits_stock.facture', verbose_name='Facture'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence du Paiement'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='gestion_produits_stock.categorie', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='code_produit',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code Produit (ex: SKU)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_fournis', to='gestion_produits_stock.fournisseur', verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='lieu_stockage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='gestion_produits_stock.lieustockage', verbose_name='Lieu de Stockage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='gestion_produits_stock.produit', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Quantité en Stock'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='date_mouvement',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du Mouvement'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='gestion_produits_stock.facture', verbose_name='Facture Liée'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE_ACHAT', 'Entrée (Achat)'), ('SORTIE_VENTE', 'Sortie (Vente)'), ('TRANSFERT', 'Transfert'), ('AJUSTEMENT_POSITIF', 'Ajustement Positif'), ('AJUSTEMENT_NEGATIF', 'Ajustement Négatif'), ('RETOUR_FOURNISSEUR', 'Retour Fournisseur'), ('RETOUR_CLIENT', 'Retour Client')], max_length=50, verbose_name='Type de Mouvement'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('produit', 'lieu_stockage')},
        ),
    ]
