# Generated by Django 5.2.4 on 2025-08-08 13:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits_stock', '0002_alter_categorie_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat"),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix de vente'),
        ),
    ]
