# Generated by Django 5.2.4 on 2025-08-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits_stock', '0003_produit_prix_achat_produit_prix_vente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['nom'], 'permissions': [('can_access_interface_vente', "Peut accéder à l'interface de vente")], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
    ]
