# Generated by Django 5.2.5 on 2025-08-09 16:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits_stock', '0004_alter_produit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['nom'], 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterModelOptions(
            name='lieustockage',
            options={'verbose_name': 'Lieu de Stockage', 'verbose_name_plural': 'Lieux de Stockage'},
        ),
        migrations.AlterModelOptions(
            name='lignefacture',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['nom'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Stock par Lieu', 'verbose_name_plural': 'Stocks par Lieux'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'verbose_name_plural': 'Mouvements de Stock'},
        ),
        migrations.RemoveField(
            model_name='facture',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='date_derniere_maj',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='lieustockage',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='lignefacture',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='lignefacture',
            name='date_derniere_maj',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='date_derniere_maj',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='reference_paiement',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='prix_vente',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='date_derniere_maj',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='facture',
        ),
        migrations.AddField(
            model_name='facture',
            name='date_echeance',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date limite de paiement de la facture.'),
        ),
        migrations.AddField(
            model_name='produit',
            name='seuil_alerte',
            field=models.IntegerField(default=10, help_text="Quantité minimale avant qu'une alerte soit déclenchée.", verbose_name="Seuil d'alerte"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_produits_stock.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_facturation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='est_payee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='lieustockage',
            name='nom',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nom du Lieu'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_facture', to='gestion_produits_stock.facture'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='prix_unitaire_negocie',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_produits_stock.produit'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='total_ligne',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits_stock.facture'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode_paiement',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('MOBILE_MONEY', 'Mobile Money')], default='ESPECES', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_produits_stock.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_produits_stock.fournisseur'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'Achat Unitaire"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix de Vente Unitaire'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='lieu_stockage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits_stock.lieustockage'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits_stock.produit'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='date_mouvement',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='lieu_stockage_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_entrants', to='gestion_produits_stock.lieustockage'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='lieu_stockage_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_sortants', to='gestion_produits_stock.lieustockage'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits_stock.produit'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('TRANSFERT', 'Transfert')], max_length=10),
        ),
    ]
